import {Link} from "react-router-dom";
import type {OfficialMatch, ThreeWayProbability} from "../types";
import EmptyState from "./EmptyState";

const triple = (value: ThreeWayProbability, percent = false) => `${percent ? (value.home * 100).toFixed(1) : value.home.toFixed(2)} / ${percent ? (value.draw * 100).toFixed(1) : value.draw.toFixed(2)} / ${percent ? (value.away * 100).toFixed(1) : value.away.toFixed(2)}${percent ? "%" : ""}`;
const bestEv = (match: OfficialMatch) => Math.max(match.ev.home, match.ev.draw, match.ev.away);
export default function MatchTable({matches}: {matches: OfficialMatch[]}) {
  if (!matches.length) return <EmptyState title="暂无官方比赛数据" />;
  return <div className="table-scroll"><table className="data-table"><thead><tr><th>比赛 ID</th><th>联赛</th><th>主队 vs 客队</th><th>开赛时间</th><th>官方 SP</th><th>最终概率</th><th>最高 EV</th><th>动态阈值</th><th>模型分歧</th><th>Critic</th><th>推荐</th><th>操作</th></tr></thead><tbody>{matches.map(match => { const available = match.prediction.probabilityAvailable; return <tr key={match.id}><td><code>{match.officialMatchId || "缺失"}</code></td><td><span className="league-tag">{match.league}</span></td><td><b>{match.homeTeam} <em>vs</em> {match.awayTeam}</b></td><td>{new Date(match.kickoffTime).toLocaleString("zh-CN", {month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit"})}</td><td>{Object.values(match.officialSp).every(value => value > 1) ? triple(match.officialSp) : "-"}</td><td title={available ? undefined : match.prediction.criticReasons.join("；")}>{available ? triple(match.prediction.finalProbability, true) : "不可用"}</td><td className={available ? bestEv(match) >= 0 ? "positive" : "negative" : ""}>{available ? `${(bestEv(match) * 100).toFixed(2)}%` : "不可用"}</td><td>{available && Number.isFinite(match.prediction.dynamicEvThreshold) ? `${(match.prediction.dynamicEvThreshold * 100).toFixed(2)}%` : "不可用"}</td><td>{available ? `${(match.prediction.modelDisagreement.maxDisagreement * 100).toFixed(1)}% / ${match.prediction.modelDisagreement.level}` : "不可用"}</td><td>{match.prediction.criticPassed ? "通过" : "拦截"}</td><td><span className={`recommend-badge ${match.recommendation === "NO_BET" ? "no-bet" : ""}`}>{match.recommendation}</span></td><td><Link className="table-action" to={`/matches/${match.id}`}>查看详情</Link></td></tr>})}</tbody></table></div>;
}
