import type {StackingEvaluationResult, StackingModelCoefficients} from "../types";
import ModelVersionBadge from "./ModelVersionBadge";
import StackingFeatureImportanceTable from "./StackingFeatureImportanceTable";
const pct = (value: number) => `${(value * 100).toFixed(2)}%`;
export default function StackingComparisonPanel({evaluation, model}: {evaluation: StackingEvaluationResult; model: StackingModelCoefficients}) {
  const rows = [["Log Loss",evaluation.baselineMetrics.logLoss,evaluation.stackingMetrics.logLoss,evaluation.logLossImprovement],["Brier Score",evaluation.baselineMetrics.brierScore,evaluation.stackingMetrics.brierScore,evaluation.brierScoreImprovement],["Calibration Error",evaluation.baselineMetrics.calibrationError,evaluation.stackingMetrics.calibrationError,evaluation.calibrationImprovement]] as const;
  const importance = model.featureNames.map((feature,index)=>({feature,contribution:Math.max(Math.abs(model.homeWeights[index]??0),Math.abs(model.drawWeights[index]??0),Math.abs(model.awayWeights[index]??0))})).sort((a,b)=>b.contribution-a.contribution).slice(0,8);
  return <section className="panel"><div className="panel-heading"><div><h2>Stacking 模型评估</h2><p>同一时间顺序测试集上的规则融合与候选模型对比。</p></div><ModelVersionBadge source="STACKING_CANDIDATE" version={model.version}/></div><div className="summary-strip backtest-inner"><span>训练样本<b>{model.trainingMatchCount}</b></span><span>验证样本<b>{model.validationMatchCount}</b></span><span>生产启用<b>否</b></span><span>Fallback 支持<b>是</b></span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>指标</th><th>Rule-based</th><th>Stacking</th><th>改善</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1].toFixed(4)}</td><td>{row[2].toFixed(4)}</td><td>{row[3].toFixed(4)}</td></tr>)}<tr><td>ROI</td><td>{pct(evaluation.baselineMetrics.roi)}</td><td>{pct(evaluation.stackingMetrics.roi)}</td><td>{pct(evaluation.roiDifference)}</td></tr><tr><td>CLV</td><td>{pct(evaluation.baselineMetrics.averageClv)}</td><td>{pct(evaluation.stackingMetrics.averageClv)}</td><td>{pct(evaluation.clvDifference)}</td></tr><tr><td>No Bet Ratio</td><td>{pct(evaluation.baselineMetrics.noBetRatio)}</td><td>{pct(evaluation.stackingMetrics.noBetRatio)}</td><td>{pct(evaluation.stackingMetrics.noBetRatio-evaluation.baselineMetrics.noBetRatio)}</td></tr></tbody></table></div><h3 className="tab-content">按联赛对比</h3><div className="table-scroll"><table className="data-table"><thead><tr><th>联赛</th><th>Baseline Log Loss</th><th>Stacking Log Loss</th><th>改善</th><th>样本</th></tr></thead><tbody>{evaluation.byLeague.map(row=><tr key={row.league}><td>{row.league}</td><td>{row.baselineLogLoss.toFixed(4)}</td><td>{row.stackingLogLoss.toFixed(4)}</td><td>{row.improvement.toFixed(4)}</td><td>{row.count}</td></tr>)}</tbody></table></div><h3 className="tab-content">Top Features</h3><StackingFeatureImportanceTable features={importance}/><div className="critic-list tab-content">{evaluation.summary.map(line=><div key={line}>{line}</div>)}</div></section>;
}
