export const AlgorithmConfig = {
  poisson: {halfLife: 90, minLambdaHome: .25, maxLambdaHome: 4, minLambdaAway: .20, maxLambdaAway: 3.5, minTeamMatches: 10, fullReliabilityMatches: 20},
  dixonColes: {defaultRho: -.10, minRho: -.18, maxRho: .02, maxGoals: 10},
  elo: {initialElo: 1500, homeAdvantage: 65, kLeague: 20, kCup: 25, kFriendly: 10},
  ensemble: {noMl: {market: .45, dixonColes: .35, elo: .20}, withMl: {market: .35, dixonColes: .30, elo: .15, ml: .20}},
  calibration: {method: "temperature" as const, defaultTemperature: 1.08},
  marketGuard: {anchorDeviation: .12, noBetDeviation: .18, anchorStrength: .50},
  critic: {baseEvThreshold: .045, maxDailyRecommendations: 5, minRecommendedOdds: 1.25, maxAllowedProbability: .88, highProbabilityWarning: .82, oddsFreshnessMinutes: {nearKickoff: 15, sameDay: 120, early: 360}},
  bankroll: {fractionalKelly: .25, maxSingleStakeRatio: .01},
};

export const teamAliasMap: Record<string, string> = {
  "曼城": "Manchester City", "曼彻斯特城": "Manchester City", "man city": "Manchester City", "manchester city fc": "Manchester City",
  "热刺": "Tottenham Hotspur", "tottenham": "Tottenham Hotspur", "spurs": "Tottenham Hotspur",
  "皇马": "Real Madrid", "皇家马德里": "Real Madrid", "real madrid cf": "Real Madrid",
  "美国": "United States", "德国": "Germany", "澳大利亚": "Australia", "瑞士": "Switzerland",
  "巴拿马": "Panama", "波黑": "Bosnia and Herzegovina", "英格兰": "England", "新西兰": "New Zealand",
  "玻利维亚": "Bolivia", "苏格兰": "Scotland", "巴西": "Brazil", "埃及": "Egypt",
  "委内瑞拉": "Venezuela", "土耳其": "Turkey", "阿根廷": "Argentina", "洪都拉斯": "Honduras",
  "克罗地亚": "Croatia", "斯洛文尼": "Slovenia", "斯洛文尼亚": "Slovenia", "摩洛哥": "Morocco",
  "挪威": "Norway", "希腊": "Greece", "意大利": "Italy", "哥伦比亚": "Colombia", "约旦": "Jordan",
  "荷兰": "Netherlands", "乌兹别克": "Uzbekistan", "乌兹别克斯坦": "Uzbekistan", "法国": "France",
  "北爱尔兰": "Northern Ireland", "秘鲁": "Peru", "西班牙": "Spain", "中国": "China", "中国队": "China",
  "泰国": "Thailand", "匈牙利": "Hungary", "哈萨克": "Kazakhstan", "哈萨克斯坦": "Kazakhstan",
  "冰岛": "Iceland", "葡萄牙": "Portugal", "尼日利亚": "Nigeria", "哥斯达": "Costa Rica",
  "哥斯达黎加": "Costa Rica", "墨西哥": "Mexico", "南非": "South Africa", "韩国": "South Korea",
  "捷克": "Czech Republic", "加拿大": "Canada", "巴拉圭": "Paraguay", "卡塔尔": "Qatar",
  "海地": "Haiti", "库拉索": "Curaçao", "日本": "Japan", "科特迪瓦": "Ivory Coast",
  "厄瓜多尔": "Ecuador", "瑞典": "Sweden", "突尼斯": "Tunisia", "佛得角": "Cape Verde",
  "比利时": "Belgium", "沙特": "Saudi Arabia", "沙特阿拉伯": "Saudi Arabia", "乌拉圭": "Uruguay",
  "伊朗": "Iran",
};
