import type {BacktestRecord, BlockedRecommendationAnalysis, EdgeBucketPerformance, TrueOddsFilterConfig, TrueOddsOptimizationResult} from "../types";
import {generateTrueOddsConfigGrid} from "./trueOddsConfig";

const mean=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const rate=(values:boolean[])=>values.length?values.filter(Boolean).length/values.length:0;
const maxDrawdown=(profits:number[])=>{let equity=0,peak=0,worst=0;for(const profit of profits){equity+=profit;peak=Math.max(peak,equity);worst=Math.max(worst,peak-equity)}return worst};
const lowerBucket=(value?:number)=>value===undefined?"UNKNOWN":value<=0?"<=0":value<=.005?"0-0.005":value<=.01?"0.005-0.01":value<=.02?"0.01-0.02":"0.02+";
const scoreBucket=(value?:number)=>value===undefined?"UNKNOWN":value<35?"0-35":value<55?"35-55":value<65?"55-65":value<75?"65-75":"75+";
const passes=(record:BacktestRecord,config:TrueOddsFilterConfig)=> {
  const edge=record.prediction.edgeQuality, agreement=record.prediction.trueOddsEstimate?.marketMultiDevig.methodAgreementScore ?? 0;
  if(!edge)return false;
  return (record.lowerBoundEv??-Infinity)>=config.lowerBoundEvMin&&edge.edgeQualityScore>=config.edgeQualityMinScore&&config.allowedEdgeQualityLevels.includes(edge.edgeQualityLevel)&&agreement>=config.minMethodAgreementScore;
};
function metrics(records:BacktestRecord[], config?:TrueOddsFilterConfig) {
  const baselineBets=records.filter(row=>row.recommendation!=="NO_BET"), bets=config?baselineBets.filter(row=>passes(row,config)):baselineBets;
  const blocked=config?baselineBets.filter(row=>!passes(row,config)):[];
  const profits=bets.map(row=>row.profit), clvs=bets.flatMap(row=>row.clv===undefined?[]:[row.clv]);
  return {sample_count:records.length,recommendation_count:bets.length,baseline_recommendation_count:baselineBets.length,no_bet_count:records.length-bets.length,no_bet_ratio:records.length?(records.length-bets.length)/records.length:0,blocked_count:blocked.length,blocked_ratio:baselineBets.length?blocked.length/baselineBets.length:0,roi:bets.length?profits.reduce((a,b)=>a+b,0)/bets.length:0,risk_adjusted_roi:bets.length?profits.reduce((a,b)=>a+b,0)/(Math.sqrt(mean(profits.map(v=>(v-mean(profits))**2)))||1):0,average_clv:mean(clvs),positive_clv_rate:rate(clvs.map(value=>value>0)),hit_rate:rate(bets.map(row=>row.hit===true)),log_loss:mean(records.map(row=>row.logLoss)),brier_score:mean(records.map(row=>row.brierScore)),calibration_error:0,max_drawdown:maxDrawdown(profits),longest_losing_streak:0,average_edge_quality_score:mean(records.flatMap(row=>row.edgeQualityScore===undefined?[]:[row.edgeQualityScore])),average_lower_bound_ev:mean(records.flatMap(row=>row.lowerBoundEv===undefined?[]:[row.lowerBoundEv])),lower_bound_ev_positive_rate:rate(records.flatMap(row=>row.lowerBoundEv===undefined?[]:[row.lowerBoundEv>0])),average_adaptive_threshold:mean(records.flatMap(row=>row.adaptiveEvThreshold===undefined?[]:[row.adaptiveEvThreshold])),high_edge_count:records.filter(row=>row.edgeQualityLevel==="HIGH").length,medium_edge_count:records.filter(row=>row.edgeQualityLevel==="MEDIUM").length,low_edge_count:records.filter(row=>row.edgeQualityLevel==="LOW").length,no_edge_count:records.filter(row=>row.edgeQualityLevel==="NO_EDGE").length};
}
function blockedAnalysis(records:BacktestRecord[],config:TrueOddsFilterConfig):BlockedRecommendationAnalysis{
  const baseline=records.filter(row=>row.recommendation!=="NO_BET"), blocked=baseline.filter(row=>!passes(row,config)), clvs=blocked.flatMap(row=>row.clv===undefined?[]:[row.clv]), profits=blocked.map(row=>row.profit);
  return{blockedCount:blocked.length,blockedRatio:baseline.length?blocked.length/baseline.length:0,blockedRoi:blocked.length?profits.reduce((a,b)=>a+b,0)/blocked.length:null,blockedAverageClv:clvs.length?mean(clvs):null,blockedPositiveClvRate:clvs.length?rate(clvs.map(v=>v>0)):null,blockedHitRate:blocked.length?rate(blocked.map(row=>row.hit===true)):null,blockedAverageExpectedEv:mean(blocked.flatMap(row=>row.ev===undefined?[]:[row.ev])),blockedAverageLowerBoundEv:mean(blocked.flatMap(row=>row.lowerBoundEv===undefined?[]:[row.lowerBoundEv])),wouldHaveLostCount:blocked.filter(row=>row.profit<0).length,wouldHaveWonCount:blocked.filter(row=>row.profit>0).length,estimatedLossAvoided:blocked.length?-profits.reduce((a,b)=>a+b,0):null,summary:[`True Odds Filter blocked ${blocked.length} recommendations.`,clvs.length?`Blocked average CLV ${(mean(clvs)*100).toFixed(2)}%.`:"Blocked CLV unavailable."],warnings:blocked.length<10?["Blocked sample is small."]:[]};
}
function bucketPerformance(records:BacktestRecord[],config:TrueOddsFilterConfig):EdgeBucketPerformance[]{
  const dims:Record<string,(row:BacktestRecord)=>string>={edgeQualityLevel:row=>row.edgeQualityLevel??"UNKNOWN",lowerBoundEV:row=>lowerBucket(row.lowerBoundEv),edgeQualityScore:row=>scoreBucket(row.edgeQualityScore),outcome:row=>row.recommendation,league:row=>row.league,marketQuality:row=>row.externalMarketQualityLevel??"UNKNOWN"};
  return Object.entries(dims).flatMap(([bucketType,getter])=>{const groups=new Map<string,BacktestRecord[]>();records.forEach(row=>groups.set(getter(row),[...(groups.get(getter(row))??[]),row]));return [...groups.entries()].map(([bucketName,rows])=>{const m=metrics(rows,config);return{bucketName,bucketType,sampleCount:rows.length,recommendationCount:m.recommendation_count,passedCount:rows.filter(row=>passes(row,config)).length,blockedCount:m.blocked_count,roi:m.roi,averageClv:m.average_clv,positiveClvRate:m.positive_clv_rate,hitRate:m.hit_rate,averageEdgeQualityScore:m.average_edge_quality_score,averageLowerBoundEv:m.average_lower_bound_ev,maxDrawdown:m.max_drawdown,warnings:rows.length<10?["Small bucket sample."]:[]}})});
}
export function runEdgeQualityOptimization(records:BacktestRecord[], configs=generateTrueOddsConfigGrid(24), options:{minSamples?:number}={}):TrueOddsOptimizationResult{
  const baseline=metrics(records), variantResults=configs.map(config=>({variantId:config.configId,name:config.name,config,metrics:metrics(records,config)}));
  const ranking=variantResults.map(row=>{let score=0;score+=Math.max(0,row.metrics.positive_clv_rate-baseline.positive_clv_rate)*25;score+=Math.max(0,row.metrics.average_clv-baseline.average_clv)*400;score+=Math.max(0,row.metrics.roi-baseline.roi)*20;score+=row.metrics.lower_bound_ev_positive_rate*10;const reasons:string[]=[];if(row.metrics.recommendation_count<30)reasons.push("recommendation_count < 30");if(row.metrics.no_bet_ratio>.9)reasons.push("no_bet_ratio > 90%");if(row.metrics.sample_count<(options.minSamples??200))reasons.push("sample_count below minimum");return{variantId:row.variantId,name:row.name,score,metrics:row.metrics,reasons,config:row.config}}).sort((a,b)=>b.score-a.score);
  const best=ranking[0],bestConfig=best?.config,decision=records.length<(options.minSamples??200)?"NEED_MORE_DATA":best&&best.metrics.positive_clv_rate>baseline.positive_clv_rate&&(best.metrics.average_clv>baseline.average_clv||best.metrics.roi>baseline.roi)?"ENABLE_FILTER_ONLY":best&&best.score>0?"SHADOW_ONLY":"KEEP_CURRENT";
  return{runId:`frontend-${Date.now()}`,createdAt:new Date().toISOString(),baselineMetrics:baseline,variantResults,bestConfig,bestVariantId:best?.variantId,ranking,blockedAnalysis:bestConfig?blockedAnalysis(records,bestConfig):blockedAnalysis(records,configs[0]),bucketPerformance:bestConfig?bucketPerformance(records,bestConfig):[],recommendedForProduction:decision==="ENABLE_FILTER_ONLY",promotionDecision:decision,promotionReasons:[decision==="ENABLE_FILTER_ONLY"?"CLV or ROI improved in sample.":"Production enablement is not recommended from this sample."],warnings:records.length<(options.minSamples??200)?["Sample size below production minimum."]:[]};
}
