import type {ExpectedGoalsOutput, HistoricalMatch, LeagueParameters, LeagueStats, MatchContext, MatchPrediction, OfficialMatch, OfficialSp, PredictionDiagnostics, TeamStats, ThreeWayEv, ThreeWayProbability} from "../types";
import {calculateFractionalKelly} from "./bankrollSizing";
import {calibrateProbabilities} from "./calibration";
import {AlgorithmConfig} from "./config";
import {calculateDynamicEvThreshold, getProbabilityByAction, limitDailyRecommendations, runCriticCheck} from "./criticRules";
import {validateHistoricalMatches, validateOfficialMatch} from "./dataValidation";
import {calculateDixonColes1X2, validateScoreMatrix} from "./dixonColesModel";
import {calculateElo1X2, getEloBeforeMatch} from "./eloModel";
import {calculateModelDisagreement, ensembleProbabilities, getDynamicEnsembleWeights, normalizeProbability} from "./ensembleModel";
import {calculateContextAdjustments} from "./featureBuilder";
import {estimateLeagueParameters} from "./leagueParameters";
import {applyMarketAnchor} from "./marketAnchor";
import {buildWeightedTeamStats} from "./poissonModel";
import {normalizeHistoricalMatches, normalizeMatchTeams} from "./teamNameNormalizer";
import {getPastMatchesOnly} from "./timeSplit";

export const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));
export const normalizeTriple = normalizeProbability;
export function calculateMarketImpliedProbability(officialSp: OfficialSp) { if (Object.values(officialSp).some(value => !Number.isFinite(value) || value <= 1)) throw new Error("官方 SP 必须全部大于 1。"); const raw = {home: 1 / officialSp.home, draw: 1 / officialSp.draw, away: 1 / officialSp.away}, sumRaw = raw.home + raw.draw + raw.away; return {probability: normalizeProbability(raw), overround: sumRaw - 1}; }
export const impliedProbabilityFromSp = (sp: OfficialSp) => calculateMarketImpliedProbability(sp).probability;
export const calculateFairOdds = (p: ThreeWayProbability): OfficialSp => ({home: 1 / p.home, draw: 1 / p.draw, away: 1 / p.away});
export const calculateEv = (p: ThreeWayProbability, sp: OfficialSp): ThreeWayEv => ({home: p.home * sp.home - 1, draw: p.draw * sp.draw - 1, away: p.away * sp.away - 1});

function expectedGoalsFromStats(params: LeagueParameters, home: ReturnType<typeof buildWeightedTeamStats>, away: ReturnType<typeof buildWeightedTeamStats>, context: MatchContext): ExpectedGoalsOutput {
  const adjustments = calculateContextAdjustments(context), warnings = [home.sampleWarning, away.sampleWarning].filter(Boolean) as string[];
  const rawHome = params.avgHomeGoals * home.attackStrength * away.defenseWeakness * adjustments.newsAdjustmentHome * adjustments.weatherAdjustment * adjustments.fatigueAdjustmentHome;
  const rawAway = params.avgAwayGoals * away.attackStrength * home.defenseWeakness * adjustments.newsAdjustmentAway * adjustments.weatherAdjustment * adjustments.fatigueAdjustmentAway;
  const lambdaHome = clamp(Number.isFinite(rawHome) ? rawHome : params.avgHomeGoals, AlgorithmConfig.poisson.minLambdaHome, AlgorithmConfig.poisson.maxLambdaHome), lambdaAway = clamp(Number.isFinite(rawAway) ? rawAway : params.avgAwayGoals, AlgorithmConfig.poisson.minLambdaAway, AlgorithmConfig.poisson.maxLambdaAway);
  if (lambdaHome !== rawHome || lambdaAway !== rawAway) warnings.push("Expected goals out of normal range and was clamped.");
  const reliability = Math.min(home.reliability, away.reliability), dataReliability = reliability >= .8 ? "HIGH" : reliability >= .4 ? "MEDIUM" : "LOW";
  return {lambdaHome, lambdaAway, dataReliability, homeSampleCount: home.matchCount, awaySampleCount: away.matchCount, warnings, adjustmentDetails: {leagueAvgHomeGoals: params.avgHomeGoals, leagueAvgAwayGoals: params.avgAwayGoals, homeAttackStrength: home.attackStrength, awayAttackStrength: away.attackStrength, homeDefenseWeakness: home.defenseWeakness, awayDefenseWeakness: away.defenseWeakness, homeAdvantageFactor: 1, newsAdjustmentHome: adjustments.newsAdjustmentHome, newsAdjustmentAway: adjustments.newsAdjustmentAway, weatherAdjustment: adjustments.weatherAdjustment, fatigueAdjustmentHome: adjustments.fatigueAdjustmentHome, fatigueAdjustmentAway: adjustments.fatigueAdjustmentAway, lineupPenalty: adjustments.lineupPenalty}};
}
export function calculateExpectedGoals(match: Pick<OfficialMatch, "league" | "homeTeam" | "awayTeam" | "kickoffTime">, historicalMatches: HistoricalMatch[], context: MatchContext): ExpectedGoalsOutput {
  const past = getPastMatchesOnly(normalizeHistoricalMatches(historicalMatches), match.kickoffTime), params = estimateLeagueParameters(past, match.league);
  return expectedGoalsFromStats(params, buildWeightedTeamStats(past, match.homeTeam, {league: match.league, cutoffTime: match.kickoffTime}), buildWeightedTeamStats(past, match.awayTeam, {league: match.league, cutoffTime: match.kickoffTime}), context);
}
const neutralDiagnostics = (): PredictionDiagnostics => ({homeMatchCount: 0, awayMatchCount: 0, leagueMatchCount: 0, teamStatsReliability: "LOW", eloReliability: "LOW", leagueReliability: "LOW", marketDeviation: {homeDeviation: 0, drawDeviation: 0, awayDeviation: 0, maxDeviation: 0}, deviationAfterAnchor: {homeDeviation: 0, drawDeviation: 0, awayDeviation: 0, maxDeviation: 0}, marketAnchored: false, ensembleWeights: {market: 1, dixonColes: 0, elo: 0}, warnings: []});
const emptyPrediction = (match: Pick<OfficialMatch, "id" | "officialMatchId">, reason: string): MatchPrediction => { const neutral = {home: 1 / 3, draw: 1 / 3, away: 1 / 3}, expectedGoals: ExpectedGoalsOutput = {lambdaHome: 0, lambdaAway: 0, warnings: [reason], adjustmentDetails: {leagueAvgHomeGoals: 1.45, leagueAvgAwayGoals: 1.15, homeAttackStrength: 1, awayAttackStrength: 1, homeDefenseWeakness: 1, awayDefenseWeakness: 1, homeAdvantageFactor: 1, newsAdjustmentHome: 1, newsAdjustmentAway: 1, weatherAdjustment: 1, fatigueAdjustmentHome: 1, fatigueAdjustmentAway: 1, lineupPenalty: 0}}, disagreement = calculateModelDisagreement([neutral, neutral, neutral]), criticReport = {passed: false, finalAction: "NO_BET" as const, reasons: [reason], warnings: [], dynamicEvThreshold: Infinity, confidenceLevel: "D" as const, riskLevel: "HIGH" as const}; return {matchId: match.id, officialMatchId: match.officialMatchId, marketProbability: neutral, dixonColesProbability: neutral, poissonProbability: neutral, eloProbability: neutral, finalProbability: neutral, anchoredProbability: neutral, expectedGoals, lambdaHome: 0, lambdaAway: 0, fairOdds: {home: 3, draw: 3, away: 3}, ev: {home: -1, draw: -1, away: -1}, topScores: [], modelDisagreement: disagreement, diagnostics: neutralDiagnostics(), dynamicEvThreshold: Infinity, criticReport, criticPassed: false, criticReasons: [reason], recommendation: "NO_BET", confidence: "D", confidenceGrade: "NO_BET", confidenceScore: 0, riskLevel: "HIGH", suggestedStake: 0, stakeFraction: 0, recommendedProbability: null, recommendedSp: null, recommendedEv: null, createdAt: new Date().toISOString()}; };

function composePrediction(match: Pick<OfficialMatch, "id" | "officialMatchId" | "status" | "officialSp" | "kickoffTime">, context: MatchContext, bankroll: number, marketResult: ReturnType<typeof calculateMarketImpliedProbability>, expectedGoals: ExpectedGoalsOutput, params: LeagueParameters, eloData: {homeElo: number; awayElo: number; homeMatchCount: number; awayMatchCount: number; reliability: "LOW" | "MEDIUM" | "HIGH"}, teamStatsReliability: "LOW" | "MEDIUM" | "HIGH"): MatchPrediction {
  const warnings = [...(expectedGoals.warnings ?? [])], dc = calculateDixonColes1X2(expectedGoals.lambdaHome, expectedGoals.lambdaAway, AlgorithmConfig.dixonColes.maxGoals, params.defaultRho), scoreValidation = validateScoreMatrix(dc.scoreMatrix);
  if (!scoreValidation.valid) warnings.push("Dixon-Coles 比分矩阵无效，已回退到基础分布。");
  const elo = calculateElo1X2(eloData.homeElo, eloData.awayElo), adjustments = calculateContextAdjustments(context), weights = getDynamicEnsembleWeights({leagueReliability: params.reliability, eloReliability: eloData.reliability, teamStatsReliability, contextRiskLevel: adjustments.contextRiskLevel, marketOverround: marketResult.overround});
  const raw = ensembleProbabilities({market: marketResult.probability, dixonColes: dc.probability, elo}, weights), calibrated = calibrateProbabilities(raw, {method: AlgorithmConfig.calibration.method, temperature: AlgorithmConfig.calibration.defaultTemperature}), anchored = applyMarketAnchor(calibrated, marketResult.probability);
  if (anchored.warning) warnings.push(anchored.warning);
  const finalProbability = Object.values(anchored.probability).every(Number.isFinite) ? normalizeProbability(anchored.probability) : (warnings.push("最终概率异常，已回退到市场概率。"), marketResult.probability);
  const fairOdds = calculateFairOdds(finalProbability), ev = calculateEv(finalProbability, match.officialSp), modelDisagreement = calculateModelDisagreement([marketResult.probability, dc.probability, elo]);
  const best = [...([{action: "HOME", ev: ev.home, odds: match.officialSp.home}, {action: "DRAW", ev: ev.draw, odds: match.officialSp.draw}, {action: "AWAY", ev: ev.away, odds: match.officialSp.away}] as const)].sort((a, b) => b.ev - a.ev)[0];
  const minutesToKickoff = (new Date(match.kickoffTime).getTime() - Date.now()) / 60000, competitionType = context.isCupOrFriendly ? "CUP" as const : "LEAGUE" as const;
  const dynamicEvThreshold = calculateDynamicEvThreshold({riskLevel: adjustments.contextRiskLevel, dataFreshness: context.dataFreshness ?? "FRESH", modelDisagreement, lineupKnown: context.lineupKnown !== false, minutesToKickoff, homeMatchCount: eloData.homeMatchCount, awayMatchCount: eloData.awayMatchCount, marketDeviation: anchored.deviationBefore, selectedOdds: best.odds, competitionType});
  const criticReport = runCriticCheck(match, {finalProbability, ev, modelDisagreement, marketDeviation: anchored.deviationBefore, homeMatchCount: eloData.homeMatchCount, awayMatchCount: eloData.awayMatchCount}, context, dynamicEvThreshold), recommendation = criticReport.finalAction;
  const recommendedProbability = recommendation === "NO_BET" ? null : getProbabilityByAction(finalProbability, recommendation), recommendedSp = recommendation === "HOME" ? match.officialSp.home : recommendation === "DRAW" ? match.officialSp.draw : recommendation === "AWAY" ? match.officialSp.away : null, recommendedEv = recommendation === "HOME" ? ev.home : recommendation === "DRAW" ? ev.draw : recommendation === "AWAY" ? ev.away : null;
  const suggestedStake = calculateFractionalKelly(recommendedProbability ?? 0, recommendedSp ?? 0, bankroll, criticReport.confidenceLevel, criticReport.riskLevel, recommendation), diagnostics: PredictionDiagnostics = {homeMatchCount: eloData.homeMatchCount, awayMatchCount: eloData.awayMatchCount, leagueMatchCount: params.matchCount, teamStatsReliability, eloReliability: eloData.reliability, leagueReliability: params.reliability, marketDeviation: anchored.deviationBefore, deviationAfterAnchor: anchored.deviationAfter, marketAnchored: anchored.anchored, ensembleWeights: weights, warnings: [...new Set(warnings)]};
  return {matchId: match.id, officialMatchId: match.officialMatchId, marketProbability: marketResult.probability, dixonColesProbability: dc.probability, poissonProbability: dc.probability, eloProbability: elo, finalProbability, anchoredProbability: anchored.probability, expectedGoals, lambdaHome: expectedGoals.lambdaHome, lambdaAway: expectedGoals.lambdaAway, fairOdds, ev, topScores: dc.topScores, modelDisagreement, diagnostics, dynamicEvThreshold, criticReport, criticPassed: criticReport.passed, criticReasons: criticReport.reasons, recommendation, confidence: criticReport.confidenceLevel, confidenceGrade: recommendation === "NO_BET" ? "NO_BET" : criticReport.confidenceLevel, confidenceScore: criticReport.confidenceLevel === "A" ? 90 : criticReport.confidenceLevel === "B" ? 75 : criticReport.confidenceLevel === "C" ? 60 : 40, riskLevel: criticReport.riskLevel, suggestedStake, stakeFraction: bankroll ? suggestedStake / bankroll : 0, recommendedProbability, recommendedSp, recommendedEv, createdAt: new Date().toISOString()};
}

export function calculateMatchPrediction(inputMatch: Pick<OfficialMatch, "id" | "officialMatchId" | "league" | "homeTeam" | "awayTeam" | "kickoffTime" | "status" | "officialSp" | "updatedAt">, historicalMatches: HistoricalMatch[], context: MatchContext, bankroll = 10_000): MatchPrediction {
  const match = normalizeMatchTeams(inputMatch), validation = validateOfficialMatch(match); if (!validation.valid) return emptyPrediction(match, validation.errors.join("；")); if (["CANCELLED", "POSTPONED", "CLOSED", "FINISHED"].includes(match.status)) return emptyPrediction(match, "比赛已取消、延期、停售或结束。");
  try { const normalized = normalizeHistoricalMatches(historicalMatches), past = getPastMatchesOnly(normalized, match.kickoffTime), checked = validateHistoricalMatches(past), params = estimateLeagueParameters(checked.validMatches, match.league), homeStats = buildWeightedTeamStats(checked.validMatches, match.homeTeam, {league: match.league, cutoffTime: match.kickoffTime}), awayStats = buildWeightedTeamStats(checked.validMatches, match.awayTeam, {league: match.league, cutoffTime: match.kickoffTime}), expectedGoals = expectedGoalsFromStats(params, homeStats, awayStats, context), eloData = getEloBeforeMatch(checked.validMatches, match), reliability = Math.min(homeStats.reliability, awayStats.reliability) >= .8 ? "HIGH" : Math.min(homeStats.reliability, awayStats.reliability) >= .4 ? "MEDIUM" : "LOW"; return composePrediction(match, context, bankroll, calculateMarketImpliedProbability(match.officialSp), expectedGoals, params, eloData, reliability); } catch (error) { return emptyPrediction(match, error instanceof Error ? error.message : "概率计算异常。"); }
}

export function calculatePredictionForMatch(match: Pick<OfficialMatch, "id" | "officialMatchId" | "league" | "homeTeam" | "awayTeam" | "kickoffTime" | "status" | "officialSp" | "updatedAt">, teams: Record<string, TeamStats> = {}, leagues: Record<string, LeagueStats> = {}, contexts: Record<string, MatchContext> = {}): MatchPrediction {
  const context = contexts[match.id] ?? {}, home = teams[match.homeTeam], away = teams[match.awayTeam], league = leagues[match.league]; if (!match.officialMatchId || ["CANCELLED", "POSTPONED", "CLOSED", "FINISHED"].includes(match.status)) return emptyPrediction(match, !match.officialMatchId ? "缺少官方比赛 ID。" : "比赛不可推荐。");
  try { const params: LeagueParameters = {league: match.league, matchCount: 0, avgHomeGoals: league?.avgHomeGoals ?? 1.45, avgAwayGoals: league?.avgAwayGoals ?? 1.15, avgTotalGoals: (league?.avgHomeGoals ?? 1.45) + (league?.avgAwayGoals ?? 1.15), homeWinRate: .45, drawRate: .27, awayWinRate: .28, baseDrawRate: .27, homeAdvantageFactor: 1.1, defaultRho: -.10, reliability: league ? "MEDIUM" : "LOW"}, avg = league?.avgTeamGoals ?? 1.3, pseudo = (stats?: TeamStats) => ({weightedGoalsFor: 0, weightedGoalsAgainst: 0, weightedMatches: stats?.recentMatches ?? 0, matchCount: stats?.recentMatches ?? 0, reliability: Math.min(1, (stats?.recentMatches ?? 0) / 20), attackStrength: stats?.recentMatches ? 1 + (stats.recentGoalsFor / stats.recentMatches / avg - 1) * Math.min(1, stats.recentMatches / 20) : 1, defenseWeakness: stats?.recentMatches ? 1 + (stats.recentGoalsAgainst / stats.recentMatches / avg - 1) * Math.min(1, stats.recentMatches / 20) : 1, sampleWarning: (stats?.recentMatches ?? 0) < 10 ? "球队历史样本不足。" : undefined}), homePseudo = pseudo(home), awayPseudo = pseudo(away), expectedGoals = expectedGoalsFromStats(params, homePseudo, awayPseudo, context), minCount = Math.min(home?.recentMatches ?? 0, away?.recentMatches ?? 0), reliability: "LOW" | "MEDIUM" | "HIGH" = minCount >= 20 ? "HIGH" : minCount >= 10 ? "MEDIUM" : "LOW"; return composePrediction(match, context, 10_000, calculateMarketImpliedProbability(match.officialSp), expectedGoals, params, {homeElo: home?.elo ?? 1500, awayElo: away?.elo ?? 1500, homeMatchCount: home?.recentMatches ?? 0, awayMatchCount: away?.recentMatches ?? 0, reliability}, reliability); } catch (error) { return emptyPrediction(match, error instanceof Error ? error.message : "概率计算异常。"); }
}
export const calculatePredictionsForOfficialPool = (pool: Parameters<typeof calculatePredictionForMatch>[0][], teams: Record<string, TeamStats> = {}, leagues: Record<string, LeagueStats> = {}, contexts: Record<string, MatchContext> = {}) => limitDailyRecommendations(pool.map(match => calculatePredictionForMatch(match, teams, leagues, contexts)));
export const emptyOfficialSp = (): OfficialSp => ({home: 0, draw: 0, away: 0});
