import type {ExternalOddsSnapshot, ExpectedGoalsOutput, HistoricalMatch, LeagueParameters, LeagueStats, MatchContext, MatchPrediction, OfficialMatch, OfficialSp, OfficialSpSnapshot, PredictionDiagnostics, PureModelBreakdown, StackingModelCoefficients, TeamStats, ThreeWayEv, ThreeWayProbability} from "../types";
import {calculateFractionalKelly} from "./bankrollSizing";
import {calibrateProbabilities} from "./calibration";
import {AlgorithmConfig} from "./config";
import {calculateDynamicEvThreshold, externalMarketThresholdAdjustment, getProbabilityByAction, limitDailyRecommendations, runCriticCheck} from "./criticRules";
import {validateHistoricalMatches, validateOfficialMatch} from "./dataValidation";
import {calculateDixonColes1X2, validateScoreMatrix} from "./dixonColesModel";
import {calculateElo1X2, getEloBeforeMatch} from "./eloModel";
import {calculateModelDisagreement, ensembleMarketAndModel, getExternalMarketEnsembleWeights, normalizeProbability} from "./ensembleModel";
import {calculateExternalMarketConsensus} from "./externalMarket";
import {calculateContextAdjustments} from "./featureBuilder";
import {estimateLeagueParameters} from "./leagueParameters";
import {applyMarketAnchor} from "./marketAnchor";
import {buildWeightedTeamStats} from "./poissonModel";
import {normalizeHistoricalMatches, normalizeMatchTeams} from "./teamNameNormalizer";
import {getPastMatchesOnly} from "./timeSplit";
import {calculateEnhancedPureModel} from "./coreFootballModel";
import {buildStackingFeatureVector} from "./stackingFeatureBuilder";
import {predictWithStackingModel} from "./stackingModel";

export const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));
export const normalizeTriple = normalizeProbability;
export function calculateMarketImpliedProbability(officialSp: OfficialSp) { if (Object.values(officialSp).some(value => !Number.isFinite(value) || value <= 1)) throw new Error("官方 SP 必须全部大于 1。"); const raw = {home: 1 / officialSp.home, draw: 1 / officialSp.draw, away: 1 / officialSp.away}, sumRaw = raw.home + raw.draw + raw.away; return {probability: normalizeProbability(raw), overround: sumRaw - 1}; }
export const impliedProbabilityFromSp = (sp: OfficialSp) => calculateMarketImpliedProbability(sp).probability;
export const calculateFairOddsFromProbability = (p: ThreeWayProbability): OfficialSp => {
  const normalized = normalizeProbability(p);
  return {home: 1 / normalized.home, draw: 1 / normalized.draw, away: 1 / normalized.away};
};
/** @deprecated Use calculateFairOddsFromProbability. */
export const calculateFairOdds = calculateFairOddsFromProbability;
export const calculateEv = (p: ThreeWayProbability, sp: OfficialSp): ThreeWayEv => ({home: p.home * sp.home - 1, draw: p.draw * sp.draw - 1, away: p.away * sp.away - 1});
export const calculatePureModelProbability = (dixonColes: ThreeWayProbability, elo: ThreeWayProbability) => normalizeProbability({
  home: dixonColes.home * .70 + elo.home * .30,
  draw: dixonColes.draw * .70 + elo.draw * .30,
  away: dixonColes.away * .70 + elo.away * .30,
});
export const calculateEdge = (probability: ThreeWayProbability, market: ThreeWayProbability): ThreeWayEv => ({
  home: probability.home - market.home, draw: probability.draw - market.draw, away: probability.away - market.away,
});
type BookmakerOddsInput = {bookmaker: string; weight?: number; odds: OfficialSp};
export function calculateExternalMarketProbability(input: Partial<OfficialSp> | BookmakerOddsInput[] | undefined, fallback: ThreeWayProbability) {
  if (Array.isArray(input)) {
    const valid = input.filter(item => (["home", "draw", "away"] as const).every(key => Number.isFinite(item.odds[key]) && item.odds[key] > 1) && (item.weight ?? 1) > 0);
    if (!valid.length) return fallback;
    const weighted = valid.map(item => ({probability: calculateMarketImpliedProbability(item.odds).probability, weight: item.weight ?? 1}));
    const totalWeight = weighted.reduce((sum, item) => sum + item.weight, 0);
    return normalizeProbability({
      home: weighted.reduce((sum, item) => sum + item.probability.home * item.weight, 0) / totalWeight,
      draw: weighted.reduce((sum, item) => sum + item.probability.draw * item.weight, 0) / totalWeight,
      away: weighted.reduce((sum, item) => sum + item.probability.away * item.weight, 0) / totalWeight,
    });
  }
  const valid = input && (["home", "draw", "away"] as const).every(key => Number.isFinite(input[key]) && Number(input[key]) > 1);
  return valid ? normalizeProbability({home: 1 / Number(input!.home), draw: 1 / Number(input!.draw), away: 1 / Number(input!.away)}) : fallback;
}

function expectedGoalsFromStats(params: LeagueParameters, home: ReturnType<typeof buildWeightedTeamStats>, away: ReturnType<typeof buildWeightedTeamStats>, context: MatchContext): ExpectedGoalsOutput {
  const adjustments = calculateContextAdjustments(context), warnings = [home.sampleWarning, away.sampleWarning].filter(Boolean) as string[];
  const rawHome = params.avgHomeGoals * home.attackStrength * away.defenseWeakness * adjustments.newsAdjustmentHome * adjustments.weatherAdjustment * adjustments.fatigueAdjustmentHome;
  const rawAway = params.avgAwayGoals * away.attackStrength * home.defenseWeakness * adjustments.newsAdjustmentAway * adjustments.weatherAdjustment * adjustments.fatigueAdjustmentAway;
  const lambdaHome = clamp(Number.isFinite(rawHome) ? rawHome : params.avgHomeGoals, AlgorithmConfig.poisson.minLambdaHome, AlgorithmConfig.poisson.maxLambdaHome), lambdaAway = clamp(Number.isFinite(rawAway) ? rawAway : params.avgAwayGoals, AlgorithmConfig.poisson.minLambdaAway, AlgorithmConfig.poisson.maxLambdaAway);
  if (lambdaHome !== rawHome || lambdaAway !== rawAway) warnings.push("Expected goals out of normal range and was clamped.");
  const reliability = Math.min(home.reliability, away.reliability), dataReliability = reliability >= .8 ? "HIGH" : reliability >= .4 ? "MEDIUM" : "LOW";
  return {lambdaHome, lambdaAway, dataReliability, homeSampleCount: home.matchCount, awaySampleCount: away.matchCount, warnings, adjustmentDetails: {leagueAvgHomeGoals: params.avgHomeGoals, leagueAvgAwayGoals: params.avgAwayGoals, homeAttackStrength: home.attackStrength, awayAttackStrength: away.attackStrength, homeDefenseWeakness: home.defenseWeakness, awayDefenseWeakness: away.defenseWeakness, homeAdvantageFactor: 1, newsAdjustmentHome: adjustments.newsAdjustmentHome, newsAdjustmentAway: adjustments.newsAdjustmentAway, weatherAdjustment: adjustments.weatherAdjustment, fatigueAdjustmentHome: adjustments.fatigueAdjustmentHome, fatigueAdjustmentAway: adjustments.fatigueAdjustmentAway, lineupPenalty: adjustments.lineupPenalty}};
}
export function calculateExpectedGoals(match: Pick<OfficialMatch, "league" | "homeTeam" | "awayTeam" | "kickoffTime">, historicalMatches: HistoricalMatch[], context: MatchContext): ExpectedGoalsOutput {
  const past = getPastMatchesOnly(normalizeHistoricalMatches(historicalMatches), match.kickoffTime), params = estimateLeagueParameters(past, match.league);
  return expectedGoalsFromStats(params, buildWeightedTeamStats(past, match.homeTeam, {league: match.league, cutoffTime: match.kickoffTime}), buildWeightedTeamStats(past, match.awayTeam, {league: match.league, cutoffTime: match.kickoffTime}), context);
}
const neutralDiagnostics = (): PredictionDiagnostics => ({homeMatchCount: 0, awayMatchCount: 0, leagueMatchCount: 0, teamStatsReliability: "LOW", eloReliability: "LOW", leagueReliability: "LOW", marketDeviation: {homeDeviation: 0, drawDeviation: 0, awayDeviation: 0, maxDeviation: 0}, deviationAfterAnchor: {homeDeviation: 0, drawDeviation: 0, awayDeviation: 0, maxDeviation: 0}, marketAnchored: false, ensembleWeights: {market: 1, externalMarket: 0, pureModel: 0}, warnings: []});
const emptyPrediction = (match: Pick<OfficialMatch, "id" | "officialMatchId"> & {officialSp?: OfficialSp}, reason: string): MatchPrediction => { const neutral = {home: 1 / 3, draw: 1 / 3, away: 1 / 3}, neutralOdds = {home: 3, draw: 3, away: 3}, deviation = {homeDeviation: 0, drawDeviation: 0, awayDeviation: 0, maxDeviation: 0}, quality = {available: false, bookmakerCount: 0, includedBookmakerCount: 0, excludedBookmakerCount: 0, averageOverround: 0, maxBookmakerDeviation: 0, officialMarketDeviation: deviation, staleCount: 0, qualityScore: 0, qualityLevel: "UNAVAILABLE" as const, warnings: ["外部市场不可用"]}, expectedGoals: ExpectedGoalsOutput = {lambdaHome: 0, lambdaAway: 0, warnings: [reason], adjustmentDetails: {leagueAvgHomeGoals: 1.45, leagueAvgAwayGoals: 1.15, homeAttackStrength: 1, awayAttackStrength: 1, homeDefenseWeakness: 1, awayDefenseWeakness: 1, homeAdvantageFactor: 1, newsAdjustmentHome: 1, newsAdjustmentAway: 1, weatherAdjustment: 1, fatigueAdjustmentHome: 1, fatigueAdjustmentAway: 1, lineupPenalty: 0}}, disagreement = calculateModelDisagreement([neutral, neutral, neutral]), criticReport = {passed: false, finalAction: "NO_BET" as const, reasons: [reason], warnings: [], dynamicEvThreshold: Infinity, confidenceLevel: "D" as const, riskLevel: "HIGH" as const}; return {matchId: match.id, officialMatchId: match.officialMatchId, officialSp: match.officialSp ?? {home: 0, draw: 0, away: 0}, probabilityAvailable: false, marketProbability: neutral, externalMarketProbability: neutral, externalMarketQuality: quality, externalMarketWarnings: quality.warnings, normalizedBookmakers: [], pureModelProbability: neutral, dixonColesProbability: neutral, poissonProbability: neutral, eloProbability: neutral, finalProbability: neutral, anchoredProbability: neutral, expectedGoals, lambdaHome: 0, lambdaAway: 0, marketFairOdds: neutralOdds, externalMarketFairOdds: neutralOdds, pureModelFairOdds: neutralOdds, finalFairOdds: neutralOdds, pureModelEdge: {home: 0, draw: 0, away: 0}, finalEdge: {home: 0, draw: 0, away: 0}, fairOdds: neutralOdds, ev: {home: -1, draw: -1, away: -1}, topScores: [], modelDisagreement: disagreement, diagnostics: {...neutralDiagnostics(), warnings: [reason]}, dynamicEvThreshold: Infinity, criticReport, criticPassed: false, criticReasons: [reason], recommendation: "NO_BET", confidence: "D", confidenceGrade: "NO_BET", confidenceScore: 0, riskLevel: "HIGH", suggestedStake: 0, stakeFraction: 0, recommendedProbability: null, recommendedSp: null, recommendedEv: null, createdAt: new Date().toISOString()}; };

function composePrediction(match: Pick<OfficialMatch, "id" | "officialMatchId" | "league" | "status" | "officialSp" | "marketOdds" | "externalBookmakerOdds" | "kickoffTime">, context: MatchContext, bankroll: number, marketResult: ReturnType<typeof calculateMarketImpliedProbability>, expectedGoals: ExpectedGoalsOutput, params: LeagueParameters, eloData: {homeElo: number; awayElo: number; homeMatchCount: number; awayMatchCount: number; reliability: "LOW" | "MEDIUM" | "HIGH"}, teamStatsReliability: "LOW" | "MEDIUM" | "HIGH", temperature = AlgorithmConfig.calibration.defaultTemperature, pureModelBreakdown?: PureModelBreakdown, stackingOptions: {useStacking?: boolean; stackingCoefficients?: StackingModelCoefficients; officialSpSnapshot?: OfficialSpSnapshot; externalOddsSnapshot?: ExternalOddsSnapshot} = {}): MatchPrediction {
  const warnings = [...(expectedGoals.warnings ?? []),...(pureModelBreakdown?.warnings??[])], dc = calculateDixonColes1X2(expectedGoals.lambdaHome, expectedGoals.lambdaAway, AlgorithmConfig.dixonColes.maxGoals, params.defaultRho), scoreValidation = validateScoreMatrix(dc.scoreMatrix);
  if (!scoreValidation.valid) warnings.push("Dixon-Coles 比分矩阵无效，已回退到基础分布。");
  const elo = calculateElo1X2(eloData.homeElo, eloData.awayElo), adjustments = calculateContextAdjustments(context);
  const externalConsensus = calculateExternalMarketConsensus(match.externalBookmakerOdds, marketResult.probability, {now: Date.parse(match.kickoffTime)});
  const externalMarketProbability = externalConsensus.probability;
  warnings.push(...externalConsensus.warnings);
  const pureModelProbability = pureModelBreakdown?.pureModelProbability??calculatePureModelProbability(dc.probability, elo), dixonProbability=pureModelBreakdown?.dixonColesProbability??dc.probability, eloProbability=pureModelBreakdown?.eloProbability??elo;
  const weights = getExternalMarketEnsembleWeights(externalConsensus.quality.qualityLevel);
  const raw = ensembleMarketAndModel(marketResult.probability, externalMarketProbability, pureModelProbability, weights);
  const marketFairOdds = calculateFairOddsFromProbability(marketResult.probability), externalMarketFairOdds = externalConsensus.fairOdds, pureModelFairOdds = calculateFairOddsFromProbability(pureModelProbability), pureModelEdge = calculateEdge(pureModelProbability, marketResult.probability);
  const features = buildStackingFeatureVector({...match, context}, {officialSp: match.officialSp, marketProbability: marketResult.probability, externalMarketProbability, pureModelProbability, dixonColesProbability: dixonProbability, eloProbability, pureModelBreakdown, marketFairOdds, externalMarketFairOdds, pureModelFairOdds, pureModelEdge, externalMarketQuality: externalConsensus.quality, lambdaHome: expectedGoals.lambdaHome, lambdaAway: expectedGoals.lambdaAway});
  const stackingPrediction = stackingOptions.useStacking ? predictWithStackingModel(features, stackingOptions.stackingCoefficients) : undefined;
  const probabilitySource = !stackingOptions.useStacking ? "RULE_BASED_ENSEMBLE" as const : stackingPrediction?.available && !stackingPrediction.fallbackUsed ? "STACKING_MODEL" as const : "STACKING_FALLBACK" as const;
  const calibrated = calibrateProbabilities(probabilitySource === "STACKING_MODEL" ? stackingPrediction!.probability : raw, {method: AlgorithmConfig.calibration.method, temperature}), anchored = applyMarketAnchor(calibrated, marketResult.probability);
  if (anchored.warning) warnings.push(anchored.warning);
  const finalProbability = Object.values(anchored.probability).every(Number.isFinite) ? normalizeProbability(anchored.probability) : (warnings.push("最终概率异常，已回退到市场概率。"), marketResult.probability);
  const finalFairOdds = calculateFairOddsFromProbability(finalProbability), finalEdge = calculateEdge(finalProbability, marketResult.probability), ev = calculateEv(finalProbability, match.officialSp), modelDisagreement = calculateModelDisagreement([marketResult.probability, externalMarketProbability, dc.probability, elo]);
  const best = [...([{action: "HOME", ev: ev.home, odds: match.officialSp.home}, {action: "DRAW", ev: ev.draw, odds: match.officialSp.draw}, {action: "AWAY", ev: ev.away, odds: match.officialSp.away}] as const)].sort((a, b) => b.ev - a.ev)[0];
  const minutesToKickoff = (new Date(match.kickoffTime).getTime() - Date.now()) / 60000, competitionType = context.isCupOrFriendly ? "CUP" as const : "LEAGUE" as const;
  const pureAdjustment=pureModelBreakdown?(pureModelBreakdown.reliability==="LOW"?.015:0)+(pureModelBreakdown.lineupImpact.riskLevel==="HIGH"?.02:0)+(pureModelBreakdown.fatigue.riskLevel==="HIGH"?.015:0)+(pureModelBreakdown.leagueParameters.reliability==="LOW"?.015:0)+(Math.min(pureModelBreakdown.homeStrength.overallReliability,pureModelBreakdown.awayStrength.overallReliability)<.5?.02:0)+(pureModelBreakdown.lambdaClamped?.015:0):0;
  const stackingDeviation = stackingPrediction ? Math.max(Math.abs(stackingPrediction.probability.home-marketResult.probability.home),Math.abs(stackingPrediction.probability.draw-marketResult.probability.draw),Math.abs(stackingPrediction.probability.away-marketResult.probability.away)) : 0;
  const stackingAdjustment = probabilitySource === "STACKING_MODEL" ? (stackingPrediction!.confidence < .05 ? .01 : 0) + (stackingDeviation > .18 ? .02 : 0) : 0;
  const dynamicEvThreshold = calculateDynamicEvThreshold({riskLevel: adjustments.contextRiskLevel, dataFreshness: context.dataFreshness ?? "FRESH", modelDisagreement, lineupKnown: context.lineupKnown !== false, minutesToKickoff, homeMatchCount: eloData.homeMatchCount, awayMatchCount: eloData.awayMatchCount, marketDeviation: anchored.deviationBefore, selectedOdds: best.odds, competitionType}) + externalMarketThresholdAdjustment(externalConsensus.quality)+pureAdjustment+stackingAdjustment;
  const criticReport = runCriticCheck(match, {finalProbability, marketProbability: marketResult.probability, pureModelProbability, pureModelBreakdown, externalMarketQuality: externalConsensus.quality, ev, modelDisagreement, marketDeviation: anchored.deviationBefore, homeMatchCount: eloData.homeMatchCount, awayMatchCount: eloData.awayMatchCount, probabilitySource, stackingPrediction, stackedProbability: stackingPrediction?.probability}, context, dynamicEvThreshold), recommendation = criticReport.finalAction;
  const recommendedProbability = recommendation === "NO_BET" ? null : getProbabilityByAction(finalProbability, recommendation), recommendedSp = recommendation === "HOME" ? match.officialSp.home : recommendation === "DRAW" ? match.officialSp.draw : recommendation === "AWAY" ? match.officialSp.away : null, recommendedEv = recommendation === "HOME" ? ev.home : recommendation === "DRAW" ? ev.draw : recommendation === "AWAY" ? ev.away : null;
  const suggestedStake = calculateFractionalKelly(recommendedProbability ?? 0, recommendedSp ?? 0, bankroll, criticReport.confidenceLevel, criticReport.riskLevel, recommendation), diagnostics: PredictionDiagnostics = {homeMatchCount: eloData.homeMatchCount, awayMatchCount: eloData.awayMatchCount, leagueMatchCount: params.matchCount, teamStatsReliability, eloReliability: eloData.reliability, leagueReliability: params.reliability, marketDeviation: anchored.deviationBefore, deviationAfterAnchor: anchored.deviationAfter, marketAnchored: anchored.anchored, ensembleWeights: weights, warnings: [...new Set(warnings)]};
  return {matchId: match.id, officialMatchId: match.officialMatchId, officialSpSnapshotId: stackingOptions.officialSpSnapshot?.id, externalOddsSnapshotId: stackingOptions.externalOddsSnapshot?.id, lifecycleStatus: context.dataFreshness === "STALE" ? "STALE" : recommendation === "NO_BET" ? "NO_BET" : "ACTIVE", officialSp: match.officialSp, externalBookmakerOdds: match.externalBookmakerOdds, probabilityAvailable: true, marketProbability: marketResult.probability, externalMarketProbability, externalMarketQuality: externalConsensus.quality, externalMarketWarnings: externalConsensus.warnings, normalizedBookmakers: externalConsensus.normalizedBookmakers, pureModelProbability, pureModelBreakdown, dixonColesProbability: dixonProbability, poissonProbability: dixonProbability, eloProbability, stackingPrediction, stackedProbability: stackingPrediction?.probability, modelVersion: stackingPrediction?.modelVersion, probabilitySource, finalProbability, anchoredProbability: anchored.probability, expectedGoals, lambdaHome: expectedGoals.lambdaHome, lambdaAway: expectedGoals.lambdaAway, marketFairOdds, externalMarketFairOdds, pureModelFairOdds, finalFairOdds, pureModelEdge, finalEdge, fairOdds: finalFairOdds, ev, topScores: dc.topScores, modelDisagreement, diagnostics, dynamicEvThreshold, criticReport, criticPassed: criticReport.passed, criticReasons: criticReport.reasons, recommendation, confidence: criticReport.confidenceLevel, confidenceGrade: recommendation === "NO_BET" ? "NO_BET" : criticReport.confidenceLevel, confidenceScore: criticReport.confidenceLevel === "A" ? 90 : criticReport.confidenceLevel === "B" ? 75 : criticReport.confidenceLevel === "C" ? 60 : 40, riskLevel: criticReport.riskLevel, suggestedStake, stakeFraction: bankroll ? suggestedStake / bankroll : 0, recommendedProbability, recommendedSp, recommendedEv, createdAt: new Date().toISOString()};
}

export function calculateMatchPrediction(rawMatch: Pick<OfficialMatch, "id" | "officialMatchId" | "league" | "homeTeam" | "awayTeam" | "kickoffTime" | "status" | "officialSp" | "marketOdds" | "externalBookmakerOdds" | "updatedAt">, historicalMatches: HistoricalMatch[], context: MatchContext, bankroll = 10_000, options: {temperature?: number; useStacking?: boolean; stackingCoefficients?: StackingModelCoefficients; officialSpSnapshot?: OfficialSpSnapshot; externalOddsSnapshot?: ExternalOddsSnapshot} = {}): MatchPrediction {
  const inputMatch = {...rawMatch, officialSp: options.officialSpSnapshot?.sp ?? rawMatch.officialSp, externalBookmakerOdds: options.externalOddsSnapshot?.bookmakerOdds ?? rawMatch.externalBookmakerOdds};
  const staleSnapshot = [options.officialSpSnapshot, options.externalOddsSnapshot].some(snapshot => snapshot && Date.now() - Date.parse(snapshot.capturedAt) > 30 * 60 * 1000);
  context = staleSnapshot ? {...context, dataFreshness: "STALE"} : context;
  const match = normalizeMatchTeams(inputMatch), validation = validateOfficialMatch(match); if (!validation.valid) return emptyPrediction(match, validation.errors.join("；")); if (["CANCELLED", "POSTPONED"].includes(match.status)) return emptyPrediction(match, "比赛已取消或延期。");
  try { const normalized=normalizeHistoricalMatches(historicalMatches),past=getPastMatchesOnly(normalized,match.kickoffTime),checked=validateHistoricalMatches(past),enhanced=calculateEnhancedPureModel(match,checked.validMatches,context),params=estimateLeagueParameters(checked.validMatches,match.league),expectedGoals:ExpectedGoalsOutput={lambdaHome:enhanced.lambdaHome,lambdaAway:enhanced.lambdaAway,dataReliability:enhanced.reliability,homeSampleCount:Math.round(enhanced.homeStrength.totalWeightedMatches),awaySampleCount:Math.round(enhanced.awayStrength.totalWeightedMatches),warnings:enhanced.warnings,adjustmentDetails:{leagueAvgHomeGoals:enhanced.leagueParameters.avgHomeGoals,leagueAvgAwayGoals:enhanced.leagueParameters.avgAwayGoals,homeAttackStrength:enhanced.homeStrength.homeAttackStrength,awayAttackStrength:enhanced.awayStrength.awayAttackStrength,homeDefenseWeakness:enhanced.homeStrength.homeDefenseWeakness,awayDefenseWeakness:enhanced.awayStrength.awayDefenseWeakness,homeAdvantageFactor:1,newsAdjustmentHome:enhanced.lineupImpact.homeAttackFactor,newsAdjustmentAway:enhanced.lineupImpact.awayAttackFactor,weatherAdjustment:1,fatigueAdjustmentHome:enhanced.fatigue.homeFatigueFactor,fatigueAdjustmentAway:enhanced.fatigue.awayFatigueFactor,lineupPenalty:enhanced.lineupImpact.totalImpactMagnitude}},eloData=getEloBeforeMatch(checked.validMatches,match);return composePrediction(match,context,bankroll,calculateMarketImpliedProbability(match.officialSp),expectedGoals,params,eloData,enhanced.reliability,options.temperature,enhanced,options); } catch (error) { return emptyPrediction(match, error instanceof Error ? error.message : "概率计算异常。"); }
}

export function calculatePredictionForMatch(match: Pick<OfficialMatch, "id" | "officialMatchId" | "league" | "homeTeam" | "awayTeam" | "kickoffTime" | "status" | "officialSp" | "marketOdds" | "externalBookmakerOdds" | "updatedAt">, teams: Record<string, TeamStats> = {}, leagues: Record<string, LeagueStats> = {}, contexts: Record<string, MatchContext> = {}): MatchPrediction {
  const context = contexts[match.id] ?? {}, home = teams[match.homeTeam], away = teams[match.awayTeam], league = leagues[match.league]; if (!match.officialMatchId || ["CANCELLED", "POSTPONED"].includes(match.status)) return emptyPrediction(match, !match.officialMatchId ? "缺少官方比赛 ID。" : "比赛已取消或延期。");
  try { const params: LeagueParameters = {league: match.league, matchCount: 0, avgHomeGoals: league?.avgHomeGoals ?? 1.45, avgAwayGoals: league?.avgAwayGoals ?? 1.15, avgTotalGoals: (league?.avgHomeGoals ?? 1.45) + (league?.avgAwayGoals ?? 1.15), homeWinRate: .45, drawRate: .27, awayWinRate: .28, baseDrawRate: .27, homeAdvantageFactor: 1.1, defaultRho: -.10, reliability: league ? "MEDIUM" : "LOW"}, avg = league?.avgTeamGoals ?? 1.3, pseudo = (stats?: TeamStats) => ({weightedGoalsFor: 0, weightedGoalsAgainst: 0, weightedMatches: stats?.recentMatches ?? 0, matchCount: stats?.recentMatches ?? 0, reliability: Math.min(1, (stats?.recentMatches ?? 0) / 20), attackStrength: stats?.recentMatches ? 1 + (stats.recentGoalsFor / stats.recentMatches / avg - 1) * Math.min(1, stats.recentMatches / 20) : 1, defenseWeakness: stats?.recentMatches ? 1 + (stats.recentGoalsAgainst / stats.recentMatches / avg - 1) * Math.min(1, stats.recentMatches / 20) : 1, sampleWarning: (stats?.recentMatches ?? 0) < 10 ? "球队历史样本不足。" : undefined}), homePseudo = pseudo(home), awayPseudo = pseudo(away), expectedGoals = expectedGoalsFromStats(params, homePseudo, awayPseudo, context), minCount = Math.min(home?.recentMatches ?? 0, away?.recentMatches ?? 0), reliability: "LOW" | "MEDIUM" | "HIGH" = minCount >= 20 ? "HIGH" : minCount >= 10 ? "MEDIUM" : "LOW"; return composePrediction(match, context, 10_000, calculateMarketImpliedProbability(match.officialSp), expectedGoals, params, {homeElo: home?.elo ?? 1500, awayElo: away?.elo ?? 1500, homeMatchCount: home?.recentMatches ?? 0, awayMatchCount: away?.recentMatches ?? 0, reliability}, reliability); } catch (error) { return emptyPrediction(match, error instanceof Error ? error.message : "概率计算异常。"); }
}
export const calculatePredictionsForOfficialPool = (pool: Parameters<typeof calculatePredictionForMatch>[0][], teams: Record<string, TeamStats> = {}, leagues: Record<string, LeagueStats> = {}, contexts: Record<string, MatchContext> = {}) => limitDailyRecommendations(pool.map(match => calculatePredictionForMatch(match, teams, leagues, contexts)));
export const emptyOfficialSp = (): OfficialSp => ({home: 0, draw: 0, away: 0});
