import type {BetOption,ConfidenceGrade,EvTriple,FairOddsTriple,LeagueStats,MatchContext,ModelPrediction,OfficialMatch,OfficialSp,ProbabilityTriple,TeamStats} from "../types";

const NEUTRAL:ProbabilityTriple={home:1/3,draw:1/3,away:1/3};
export const clamp=(value:number,min:number,max:number)=>Number.isFinite(value)?Math.max(min,Math.min(max,value)):min;
export function normalizeTriple(value:ProbabilityTriple):ProbabilityTriple{const v={home:Math.max(0,value.home||0),draw:Math.max(0,value.draw||0),away:Math.max(0,value.away||0)},sum=v.home+v.draw+v.away;return sum?{home:v.home/sum,draw:v.draw/sum,away:v.away/sum}:{...NEUTRAL}}
export function impliedProbabilityFromSp(sp:OfficialSp):ProbabilityTriple{return Object.values(sp).every(v=>Number.isFinite(v)&&v>1)?normalizeTriple({home:1/sp.home,draw:1/sp.draw,away:1/sp.away}):{...NEUTRAL}}
const factorial=(n:number)=>{let result=1;for(let i=2;i<=n;i++)result*=i;return result};
export function poissonPmf(k:number,lambda:number):number{return Number.isInteger(k)&&k>=0?Math.exp(-lambda)*lambda**k/factorial(k):0}
export function calculatePoisson1x2(lambdaHome:number,lambdaAway:number,maxGoals=10):ProbabilityTriple{let home=0,draw=0,away=0;const lh=clamp(lambdaHome,.2,4.5),la=clamp(lambdaAway,.2,4.5);for(let h=0;h<=maxGoals;h++)for(let a=0;a<=maxGoals;a++){const p=poissonPmf(h,lh)*poissonPmf(a,la);if(h>a)home+=p;else if(h===a)draw+=p;else away+=p}return normalizeTriple({home,draw,away})}
export function calculateElo1x2(homeElo:number,awayElo:number,homeAdvantageElo=65):ProbabilityTriple{const diff=(homeElo||1500)+homeAdvantageElo-(awayElo||1500),draw=clamp(.27*Math.exp(-Math.abs(diff)/500),.12,.32),homeNoDraw=1/(1+10**(-diff/400));return normalizeTriple({home:(1-draw)*homeNoDraw,draw,away:(1-draw)*(1-homeNoDraw)})}
export function calculateTeamStrength(team:TeamStats|undefined,league:LeagueStats){if(!team||team.recentMatches<5)return{attackStrength:1,defenseWeakness:1,elo:team?.elo??1500};const avg=league.avgTeamGoals||1.3;return{attackStrength:clamp(team.recentGoalsFor/avg,.55,1.85),defenseWeakness:clamp(team.recentGoalsAgainst/avg,.55,1.85),elo:team.elo||1500}}
export function calculateExpectedGoals(match:Pick<OfficialMatch,"league">,homeStats?:TeamStats,awayStats?:TeamStats,leagueStats?:LeagueStats,context:MatchContext={}){const league=leagueStats??{league:match.league,avgHomeGoals:1.45,avgAwayGoals:1.15,avgTeamGoals:1.3},home=calculateTeamStrength(homeStats,league),away=calculateTeamStrength(awayStats,league),weather=clamp(context.weatherGoalFactor??1,.85,1.08);return{lambdaHome:clamp(league.avgHomeGoals*home.attackStrength*away.defenseWeakness*1.06*(context.homeNewsAdjustment??1)*weather*(context.scheduleFatigueFactorHome??1),.2,4.5),lambdaAway:clamp(league.avgAwayGoals*away.attackStrength*home.defenseWeakness*(context.awayNewsAdjustment??1)*weather*(context.scheduleFatigueFactorAway??1),.2,4.5)}}
export function ensembleProbabilities(market:ProbabilityTriple,poisson:ProbabilityTriple,elo:ProbabilityTriple,weights={market:.45,poisson:.35,elo:.2}){return normalizeTriple({home:market.home*weights.market+poisson.home*weights.poisson+elo.home*weights.elo,draw:market.draw*weights.market+poisson.draw*weights.poisson+elo.draw*weights.elo,away:market.away*weights.market+poisson.away*weights.poisson+elo.away*weights.elo})}
export function calculateFairOdds(p:ProbabilityTriple):FairOddsTriple{return{home:p.home>0?1/p.home:999,draw:p.draw>0?1/p.draw:999,away:p.away>0?1/p.away:999}}
export function calculateEv(p:ProbabilityTriple,sp:OfficialSp):EvTriple{const ev=(prob:number,odds:number)=>odds>1?prob*odds-1:-1;return{home:ev(p.home,sp.home),draw:ev(p.draw,sp.draw),away:ev(p.away,sp.away)}}
export function calculateModelDisagreement(...models:ProbabilityTriple[]):number{return Math.max(...(["home","draw","away"] as const).map(k=>Math.max(...models.map(m=>m[k]))-Math.min(...models.map(m=>m[k]))))}
const minutesSince=(iso:string)=>{const time=new Date(iso).getTime();return Number.isFinite(time)?Math.max(0,(Date.now()-time)/60000):Infinity};
export function runCriticChecks(match:Pick<OfficialMatch,"officialMatchId"|"status"|"officialSp"|"updatedAt">,draft:{finalProbability:ProbabilityTriple;ev:EvTriple;modelDisagreement:number},context:MatchContext={}){const reasons:string[]=[];if(!match.officialMatchId)reasons.push("缺少官方比赛ID，不允许进入模型");if(!["NOT_STARTED","LIVE"].includes(match.status))reasons.push(`比赛状态不可推荐：${match.status}`);if(Object.values(match.officialSp).some(v=>!Number.isFinite(v)||v<=1))reasons.push("官方胜平负 SP 无效");if(minutesSince(match.updatedAt)>10)reasons.push("官方赔率更新时间超过10分钟");const values=Object.values(draft.finalProbability);if(Math.abs(values.reduce((a,b)=>a+b,0)-1)>.001)reasons.push("最终概率之和不等于1");if(values.some(v=>!Number.isFinite(v)||v<0||v>1))reasons.push("最终概率存在非法值");if(draft.modelDisagreement>.12)reasons.push("模型分歧超过12%，不推荐");if(Math.max(...Object.values(draft.ev))<.05)reasons.push("最高 EV 低于5%阈值");if(context.newsReliability==="LOW")reasons.push("新闻可信度低");if(context.lineupKnown===false)reasons.push("临场阵容未知");if(context.riskLimitTriggered)reasons.push("触发风险上限");return{passed:reasons.length===0,reasons}}
export function makeRecommendation(match:Pick<OfficialMatch,"status"|"officialMatchId"|"officialSp">,p:ProbabilityTriple,ev:EvTriple,critic:{passed:boolean}){if(!critic.passed||!match.officialMatchId||!["NOT_STARTED","LIVE"].includes(match.status))return{recommendation:"NO_BET" as BetOption,recommendedProbability:null,recommendedSp:null,recommendedEv:null};const rows=[{recommendation:"HOME" as BetOption,p:p.home,sp:match.officialSp.home,ev:ev.home},{recommendation:"DRAW" as BetOption,p:p.draw,sp:match.officialSp.draw,ev:ev.draw},{recommendation:"AWAY" as BetOption,p:p.away,sp:match.officialSp.away,ev:ev.away}].sort((a,b)=>b.ev-a.ev);const best=rows[0];return best.ev>=.05?{recommendation:best.recommendation,recommendedProbability:best.p,recommendedSp:best.sp,recommendedEv:best.ev}:{recommendation:"NO_BET" as BetOption,recommendedProbability:null,recommendedSp:null,recommendedEv:null}}
export function calculateConfidenceScore({modelDisagreement,updatedAt,context={},recommendedEv,hasHistoricalData}:{modelDisagreement:number;updatedAt:string;context?:MatchContext;recommendedEv:number|null;hasHistoricalData:boolean}):{score:number;grade:Exclude<ConfidenceGrade,"NO_BET">}{let score=100;if(modelDisagreement>.08)score-=15;if(minutesSince(updatedAt)>5)score-=10;if(context.newsReliability==="LOW")score-=15;if(context.lineupKnown===false)score-=10;if(recommendedEv!==null&&recommendedEv<.07)score-=8;if(context.isCupOrFriendly)score-=8;if(!hasHistoricalData)score-=10;score=clamp(score,0,100);return{score,grade:score>=85?"A":score>=70?"B":score>=55?"C":"D"}}
export function calculateStakeFraction(probability:number,odds:number,recommendation:BetOption){if(recommendation==="NO_BET"||odds<=1)return 0;return clamp(Math.max(0,(probability*odds-1)/(odds-1))*.25,0,.01)}
function emptyPrediction(match:Pick<OfficialMatch,"id"|"officialMatchId">,reasons:string[]):ModelPrediction{return{matchId:match.id,officialMatchId:match.officialMatchId,marketProbability:{...NEUTRAL},poissonProbability:{...NEUTRAL},eloProbability:{...NEUTRAL},finalProbability:{...NEUTRAL},lambdaHome:0,lambdaAway:0,fairOdds:{home:3,draw:3,away:3},ev:{home:-1,draw:-1,away:-1},modelDisagreement:0,criticPassed:false,criticReasons:reasons,recommendation:"NO_BET",recommendedProbability:null,recommendedSp:null,recommendedEv:null,confidenceScore:0,confidenceGrade:"NO_BET",stakeFraction:0,createdAt:new Date().toISOString()}}
export function calculatePredictionForMatch(match:Pick<OfficialMatch,"id"|"officialMatchId"|"league"|"homeTeam"|"awayTeam"|"status"|"officialSp"|"updatedAt">,teamStatsMap:Record<string,TeamStats>={},leagueStatsMap:Record<string,LeagueStats>={},contextMap:Record<string,MatchContext>={}):ModelPrediction{try{if(!match.officialMatchId)return emptyPrediction(match,["缺少官方比赛ID，不允许进入模型"]);const context=contextMap[match.id]??{},home=teamStatsMap[match.homeTeam],away=teamStatsMap[match.awayTeam],league=leagueStatsMap[match.league],market=impliedProbabilityFromSp(match.officialSp),expected=calculateExpectedGoals(match,home,away,league,context),poisson=calculatePoisson1x2(expected.lambdaHome,expected.lambdaAway),fallback=league??{league:match.league,avgHomeGoals:1.45,avgAwayGoals:1.15,avgTeamGoals:1.3},elo=calculateElo1x2(calculateTeamStrength(home,fallback).elo,calculateTeamStrength(away,fallback).elo),finalProbability=ensembleProbabilities(market,poisson,elo),fairOdds=calculateFairOdds(finalProbability),ev=calculateEv(finalProbability,match.officialSp),modelDisagreement=calculateModelDisagreement(market,poisson,elo),critic=runCriticChecks(match,{finalProbability,ev,modelDisagreement},context),decision=makeRecommendation(match,finalProbability,ev,critic),confidence=calculateConfidenceScore({modelDisagreement,updatedAt:match.updatedAt,context,recommendedEv:decision.recommendedEv,hasHistoricalData:Boolean(home&&away&&home.recentMatches>=5&&away.recentMatches>=5)});return{matchId:match.id,officialMatchId:match.officialMatchId,marketProbability:market,poissonProbability:poisson,eloProbability:elo,finalProbability,lambdaHome:expected.lambdaHome,lambdaAway:expected.lambdaAway,fairOdds,ev,modelDisagreement,criticPassed:critic.passed,criticReasons:critic.reasons,recommendation:decision.recommendation,recommendedProbability:decision.recommendedProbability,recommendedSp:decision.recommendedSp,recommendedEv:decision.recommendedEv,confidenceScore:confidence.score,confidenceGrade:decision.recommendation==="NO_BET"?"NO_BET":confidence.grade,stakeFraction:calculateStakeFraction(decision.recommendedProbability??0,decision.recommendedSp??0,decision.recommendation),createdAt:new Date().toISOString()}}catch(error){return emptyPrediction(match,[`概率计算异常：${error instanceof Error?error.message:"未知错误"}`])}}
export function calculatePredictionsForOfficialPool(pool:Array<Pick<OfficialMatch,"id"|"officialMatchId"|"league"|"homeTeam"|"awayTeam"|"status"|"officialSp"|"updatedAt">>,teams:Record<string,TeamStats>={},leagues:Record<string,LeagueStats>={},contexts:Record<string,MatchContext>={}){return pool.map(match=>calculatePredictionForMatch(match,teams,leagues,contexts))}
export const emptyOfficialSp=():OfficialSp=>({home:0,draw:0,away:0});
