import {useState} from "react";
import PageHeader from "../components/PageHeader";
import useApi from "../hooks/useApi";
type Overview = {counts: Record<string, number>; agents: Array<{name: string; state: string; task_count: number; last_updated: string | null}>};
const labels: Record<string, string> = {matches: "官方比赛", historical_matches: "历史比赛", official_odds: "官方 SP 快照", market_odds: "外部赔率快照", news: "新闻情报", weather: "天气快照", features: "球队特征", predictions: "模型预测", signals: "决策信号", backtests: "回测报告"};
export default function DataCenterPage() {
  const {data, loading, error} = useApi<Overview>("/api/system/overview", {counts: {}, agents: []}), [file, setFile] = useState<File | null>(null), [message, setMessage] = useState("");
  const upload = async () => { if (!file) { setMessage("请先选择历史 CSV"); return; } const form = new FormData(); form.append("file", file); setMessage("正在导入历史数据..."); const response = await fetch("/api/historical-matches/upload-csv", {method: "POST", body: form}); if (!response.ok) { setMessage(`导入失败：${await response.text()}`); return; } const report = await response.json(); setMessage(`导入完成：新增 ${report.imported}，更新 ${report.updated}，丢弃 ${report.dropped}；历史库共 ${report.matches} 场`); };
  const sync = async () => { setMessage("历史数据 Agent 正在同步公开真实赛果..."); const response = await fetch("/api/historical-matches/sync", {method: "POST"}); if (!response.ok) { setMessage(`同步失败：${await response.text()}`); return; } const report = await response.json(); setMessage(`同步完成：下载 ${report.downloaded} 个 CSV，新增 ${report.imported}，更新 ${report.updated}，历史库共 ${report.database_matches} 场`); };
  return <div className="page"><PageHeader title="数据中心" subtitle="历史比赛落库后直接驱动 V4 联赛参数、动态 Elo 与时间衰减模型" /><section className="panel" style={{marginBottom: 16}}><div className="panel-heading"><div><h2>历史数据 Agent</h2><p>自动同步公开真实赛果，也可手动导入合法 CSV</p></div><button onClick={sync}>立即同步真实赛果</button></div><div className="filter-bar"><input type="file" accept=".csv" onChange={event => setFile(event.target.files?.[0] ?? null)} /><button onClick={upload}>导入历史 CSV</button>{message && <span>{message}</span>}</div></section>{loading ? <p className="empty-state">加载中...</p> : error ? <p className="empty-state">{error}</p> : <div className="data-source-grid">{Object.entries(labels).map(([key, name]) => <article className="panel data-source-card" key={key}><div><h3>{name}</h3><span className={`source-status ${data.counts[key] > 0 ? "正常" : "待接入"}`}>{data.counts[key] > 0 ? "正常" : "待接入"}</span></div><dl><div><dt>记录数</dt><dd>{(data.counts[key] ?? 0).toLocaleString()}</dd></div><div><dt>数据质量</dt><dd>{data.counts[key] > 0 ? "已落库" : "无数据"}</dd></div><div><dt>来源</dt><dd>后端数据库</dd></div><div><dt>状态</dt><dd>{data.counts[key] > 0 ? "可查询" : "等待数据"}</dd></div></dl></article>)}</div>}</div>;
}
