import {Link, useParams} from "react-router-dom";
import EmptyState from "../components/EmptyState";
import RiskTag from "../components/RiskTag";
import StatusTag from "../components/StatusTag";
import useOfficialMatches from "../hooks/useOfficialMatches";
import type {ThreeWayProbability} from "../types";

const labels = {home: "主胜", draw: "平局", away: "客胜"} as const;
const actions = {home: "HOME", draw: "DRAW", away: "AWAY"} as const;
const pct = (value: number) => Number.isFinite(value) ? `${(value * 100).toFixed(1)}%` : "禁止推荐";
const modelRow = (name: string, p: ThreeWayProbability) => <tr><th>{name}</th><td>{pct(p.home)}</td><td>{pct(p.draw)}</td><td>{pct(p.away)}</td></tr>;

export default function MatchDetailPage() {
  const {matchId} = useParams(), {matches, loading, error} = useOfficialMatches(), match = matches.find(item => item.id === matchId);
  if (loading) return <div className="page"><EmptyState title="正在加载官方比赛..." /></div>;
  if (error || !match) return <div className="page"><EmptyState title="比赛不存在或官方数据加载失败" description={error || "请从官方比赛池选择有效比赛"} /><Link className="primary-link" to="/matches">返回比赛池</Link></div>;
  const prediction = match.prediction, details = prediction.expectedGoals.adjustmentDetails, diagnostics = prediction.diagnostics;
  return <div className="page detail-page"><div className="detail-hero"><div><Link to="/matches">返回比赛池</Link><p>{match.league} · {match.officialMatchId}</p><h1>{match.homeTeam} <em>vs</em> {match.awayTeam}</h1><span>{new Date(match.kickoffTime).toLocaleString("zh-CN")} · 更新于 {new Date(match.updatedAt).toLocaleString("zh-CN")}</span></div><div><StatusTag status={match.status} /><RiskTag level={prediction.riskLevel} /></div></div><div className="detail-layout"><main>
    <section className="probability-grid">{(["home", "draw", "away"] as const).map(key => <article className={`probability-card ${prediction.recommendation === actions[key] ? "selected" : ""}`} key={key}><span>{labels[key]}</span><strong>{pct(prediction.finalProbability[key])}</strong><dl><div><dt>公平赔率</dt><dd>{prediction.fairOdds[key].toFixed(2)}</dd></div><div><dt>官方 SP</dt><dd>{match.officialSp[key] > 1 ? match.officialSp[key].toFixed(2) : "暂无"}</dd></div><div><dt>EV</dt><dd>{`${prediction.ev[key] >= 0 ? "+" : ""}${pct(prediction.ev[key])}`}</dd></div><div><dt>推荐项</dt><dd>{prediction.recommendation === actions[key] ? "是" : "否"}</dd></div></dl></article>)}</section>
    <section className="panel tabs-panel"><div className="panel-heading"><div><h2>模型分解</h2><p>权重根据联赛、Elo、球队样本和市场水位动态调整</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>模型</th><th>主胜</th><th>平局</th><th>客胜</th></tr></thead><tbody>{modelRow("官方 SP 隐含概率", prediction.marketProbability)}{modelRow("Dixon-Coles", prediction.dixonColesProbability)}{modelRow("Elo", prediction.eloProbability)}{modelRow("市场锚定概率", prediction.anchoredProbability)}{modelRow("最终概率", prediction.finalProbability)}</tbody></table></div></section>
    <section className="panel tabs-panel"><div className="panel-heading"><div><h2>诊断解释</h2><p>解释预测为何被接受、锚定或拦截</p></div></div><div className="summary-strip" style={{padding: 16, margin: 0}}><span>主队历史样本<b>{diagnostics.homeMatchCount}</b></span><span>客队历史样本<b>{diagnostics.awayMatchCount}</b></span><span>联赛历史样本<b>{diagnostics.leagueMatchCount}</b></span><span>数据新鲜度<b>{match.context?.dataFreshness ?? "STALE"}</b></span><span>球队数据可靠性<b>{diagnostics.teamStatsReliability}</b></span><span>Elo 可靠性<b>{diagnostics.eloReliability}</b></span><span>联赛参数可靠性<b>{diagnostics.leagueReliability}</b></span><span>市场锚定<b>{diagnostics.marketAnchored ? "已触发" : "未触发"}</b></span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>诊断项</th><th>主胜</th><th>平局</th><th>客胜</th><th>最大值</th></tr></thead><tbody><tr><th>模型分歧</th><td>{pct(prediction.modelDisagreement.homeDisagreement)}</td><td>{pct(prediction.modelDisagreement.drawDisagreement)}</td><td>{pct(prediction.modelDisagreement.awayDisagreement)}</td><td>{pct(prediction.modelDisagreement.maxDisagreement)} / {prediction.modelDisagreement.level}</td></tr><tr><th>市场偏离（锚定前）</th><td>{pct(diagnostics.marketDeviation.homeDeviation)}</td><td>{pct(diagnostics.marketDeviation.drawDeviation)}</td><td>{pct(diagnostics.marketDeviation.awayDeviation)}</td><td>{pct(diagnostics.marketDeviation.maxDeviation)}</td></tr><tr><th>市场偏离（锚定后）</th><td>{pct(diagnostics.deviationAfterAnchor.homeDeviation)}</td><td>{pct(diagnostics.deviationAfterAnchor.drawDeviation)}</td><td>{pct(diagnostics.deviationAfterAnchor.awayDeviation)}</td><td>{pct(diagnostics.deviationAfterAnchor.maxDeviation)}</td></tr></tbody></table></div><div className="critic-list tab-content">{diagnostics.warnings.map(warning => <div key={warning}>{warning}</div>)}</div></section>
    <section className="panel tabs-panel"><div className="panel-heading"><div><h2>预期进球调整明细</h2><p>已移除重复主场优势，样本不足时攻防强度向 1.0 回归</p></div></div><div className="weather-grid tab-content">{Object.entries(details).map(([key, value]) => <span key={key}>{key}<b>{Number(value).toFixed(3)}</b></span>)}</div></section>
    <section className="panel tabs-panel"><div className="panel-heading"><div><h2>最可能比分</h2><p>Dixon-Coles 联赛 rho 修正后的前 10 项</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>比分</th><th>概率</th></tr></thead><tbody>{prediction.topScores.map(score => <tr key={`${score.homeGoals}-${score.awayGoals}`}><td>{score.homeGoals} : {score.awayGoals}</td><td>{pct(score.probability)}</td></tr>)}</tbody></table></div></section>
    <section className="panel tabs-panel"><div className="panel-heading"><div><h2>Critic 报告</h2><p>{prediction.criticReport.passed ? "推荐成立条件已满足" : "不推荐原因"}</p></div></div><div className="critic-list tab-content">{prediction.criticReport.reasons.map(reason => <div className="fail" key={reason}>{reason}</div>)}{prediction.criticReport.warnings.map(warning => <div key={warning}>{warning}</div>)}{prediction.criticReport.passed && <div>检查通过，最终动作：{prediction.criticReport.finalAction}</div>}</div></section>
  </main><aside className="decision-panel panel"><h2>推荐决策</h2><span className={`decision-result ${prediction.recommendation === "NO_BET" ? "blocked" : ""}`}>{prediction.recommendation}</span>{prediction.recommendation === "NO_BET" && <p>{prediction.criticReport.reasons.join("；") || "不满足推荐条件"}</p>}<dl><div><dt>置信等级</dt><dd>{prediction.confidence}</dd></div><div><dt>建议仓位</dt><dd>¥{prediction.suggestedStake.toFixed(2)} ({(prediction.stakeFraction * 100).toFixed(2)}%)</dd></div><div><dt>最佳 EV</dt><dd>{prediction.recommendedEv === null ? "-" : pct(prediction.recommendedEv)}</dd></div><div><dt>动态阈值</dt><dd>{pct(prediction.dynamicEvThreshold)}</dd></div><div><dt>风险等级</dt><dd>{prediction.riskLevel}</dd></div></dl></aside></div></div>;
}
