import {useMemo, useState} from "react";
import {Link} from "react-router-dom";
import FilterBar from "../components/FilterBar";
import ModelVersionBadge from "../components/ModelVersionBadge";
import PageHeader from "../components/PageHeader";
import RecommendationStatusBadge from "../components/RecommendationStatusBadge";
import StakeRecommendationPanel from "../components/StakeRecommendationPanel";
import useOfficialMatches from "../hooks/useOfficialMatches";
import type {RecommendationLifecycleStatus} from "../types";
const lifecycle=(recommendation:string,value?:RecommendationLifecycleStatus):RecommendationLifecycleStatus=>value??(recommendation==="NO_BET"?"NO_BET":"ACTIVE");
export default function RecommendationPage(){const {matches,loading,error}=useOfficialMatches(),[showAll,setShowAll]=useState(false),[selected,setSelected]=useState("");const filtered=useMemo(()=>matches.filter(match=>showAll||(lifecycle(match.recommendation,match.prediction.lifecycleStatus)==="ACTIVE"&&match.prediction.stakeRecommendation?.status!=="STAKE_BLOCKED")),[matches,showAll]);const selectedMatch=matches.find(match=>match.id===selected)??filtered[0];return <div className="page"><PageHeader title="推荐中心" subtitle="默认只显示 ACTIVE 且未被资金风控阻断的推荐。"/><section className="summary-strip"><span>全部比赛<b>{matches.length}</b></span><span>ACTIVE<b>{matches.filter(match=>lifecycle(match.recommendation,match.prediction.lifecycleStatus)==="ACTIVE").length}</b></span><span>Stake Reduced<b>{matches.filter(match=>match.prediction.stakeRecommendation?.status==="STAKE_REDUCED").length}</b></span><span>Stake Blocked<b>{matches.filter(match=>match.prediction.stakeRecommendation?.status==="STAKE_BLOCKED").length}</b></span></section><section className="panel"><p>建议额度仅用于风险管理参考，不代表自动下注。系统不会执行任何投注操作。</p><FilterBar><label><input type="checkbox" checked={showAll} onChange={event=>setShowAll(event.target.checked)}/> 显示全部生命周期和 stake 状态</label></FilterBar>{loading?<p className="empty-state">正在计算...</p>:error?<p className="empty-state">{error}</p>:<div className="table-scroll"><table className="data-table"><thead><tr><th>比赛</th><th>概率来源</th><th>最终概率</th><th>EV</th><th>推荐</th><th>Stake</th><th>Kelly</th><th>Capped By</th><th>状态</th><th>操作</th></tr></thead><tbody>{filtered.map(match=>{const stake=match.prediction.stakeRecommendation;return <tr key={match.id}><td><b>{match.homeTeam} vs {match.awayTeam}</b><br/><code>{match.officialMatchId}</code></td><td><ModelVersionBadge source={match.prediction.probabilitySource} version={match.prediction.modelVersion}/></td><td>{Object.values(match.prediction.finalProbability).map(value=>`${(value*100).toFixed(1)}%`).join(" / ")}</td><td>{Object.values(match.prediction.ev).map(value=>`${(value*100).toFixed(1)}%`).join(" / ")}</td><td>{match.recommendation}</td><td>{stake?`${stake.finalStake.toFixed(2)} (${(stake.stakePctOfBankroll*100).toFixed(2)}%)`:"-"}</td><td>{stake?`${(stake.kelly.fractionalKellyFraction*100).toFixed(2)}%`:"-"}</td><td>{stake?.cappedBy??"-"}</td><td><RecommendationStatusBadge status={lifecycle(match.recommendation,match.prediction.lifecycleStatus)}/><br/>{stake?.status??"-"}</td><td><button onClick={()=>setSelected(match.id)}>额度解释</button> <Link className="table-action" to={`/matches/${match.id}`}>详情</Link></td></tr>})}</tbody></table></div>}</section>{selectedMatch&&<StakeRecommendationPanel stake={selectedMatch.prediction.stakeRecommendation}/>}</div>}
